# Generated by Django 5.2.5 on 2026-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
